# tasks file for ec2
---
- name: start an instance with a public IP address
  vars:
    type: t2.micro
  amazon.aws.ec2_instance:
    name: "ansible-instance"
    instance_type: "{{ type }}"
    security_group: "{{ sc_group }}"
    region: "{{ region }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    image_id: "{{ image }}"
    network:
      assign_public_ip: true
